### ISSUE TITLE
OPTIONS request using CORS plugin throws "DOMException"

### ISSUE THREAD

**Issue by danew** [fastify/fastify-routes-stats#94]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

3.3.0

### Node.js version

16.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6.1

### Description

Currently having an issue with this plugin were it is throwing an exception on an OPTIONS request.

When sending an OPTIONS request i get the following error:
```
[1671197987834] INFO (80457 on Danes-MBP-2.lan): incoming request
    reqId: "req-1"
    req: {
      "method": "OPTIONS",
      "url": "/",
      "hostname": "localhost:8080",
      "remoteAddress": "127.0.0.1",
      "remotePort": 64770
    }
[1671197987835] INFO (80457 on Danes-MBP-2.lan): The "on-request-undefined" performance mark has not been set
    reqId: "req-1"
    res: {
      "statusCode": 400
    }
    err: {
      "type": "DOMException",
      "message": "The \"on-request-undefined\" performance mark has not been set",
      "stack":
          SyntaxError: The "on-request-undefined" performance mark has not been set
              at new DOMException (node:internal/per_context/domexception:72:5)
              at __node_internal_ (node:internal/util:497:10)
              at getMark (node:internal/perf/usertiming:58:11)
              at calculateStartDuration (node:internal/perf/usertiming:141:13)
              at EventTarget.measure (node:internal/perf/usertiming:159:7)
              at Object.<anonymous> (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/@fastify/routes-stats/index.js:51:17)
              at next (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/hooks.js:219:30)
              at onSendHookRunner (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/hooks.js:241:3)
              at onSendHook (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/reply.js:521:5)
              at Reply.send (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/reply.js:196:3)
      "name": "SyntaxError",
      "code": 12,
      "INDEX_SIZE_ERR": 1,
      "DOMSTRING_SIZE_ERR": 2,
      "HIERARCHY_REQUEST_ERR": 3,
      "WRONG_DOCUMENT_ERR": 4,
      "INVALID_CHARACTER_ERR": 5,
      "NO_DATA_ALLOWED_ERR": 6,
      "NO_MODIFICATION_ALLOWED_ERR": 7,
      "NOT_FOUND_ERR": 8,
      "NOT_SUPPORTED_ERR": 9,
      "INUSE_ATTRIBUTE_ERR": 10,
      "INVALID_STATE_ERR": 11,
      "SYNTAX_ERR": 12,
      "INVALID_MODIFICATION_ERR": 13,
      "NAMESPACE_ERR": 14,
      "INVALID_ACCESS_ERR": 15,
      "VALIDATION_ERR": 16,
      "TYPE_MISMATCH_ERR": 17,
      "SECURITY_ERR": 18,
      "NETWORK_ERR": 19,
      "ABORT_ERR": 20,
      "URL_MISMATCH_ERR": 21,
      "QUOTA_EXCEEDED_ERR": 22,
      "TIMEOUT_ERR": 23,
      "INVALID_NODE_TYPE_ERR": 24,
      "DATA_CLONE_ERR": 25
    }
[1671197987838] INFO (80457 on Danes-MBP-2.lan): request completed
    reqId: "req-1"
    res: {
      "statusCode": 400
    }
    responseTime: 3.5796658992767334
``` 

### Steps to Reproduce

```js
// app.js

const routeStats = require("@fastify/routes-stats");
const fastifyCors = require("@fastify/cors");

module.exports = async function (fastify, opts) {
  fastify.register(fastifyCors);
  fastify.register(routeStats);

  fastify.post(
    "/test",
    function () {
      return {
        message: "Success.",
      };
    }
  );
}
```
Run `fastify start -p 8080 -l info -P app.js`
Then run `curl -X OPTIONS http://localhost:8080/`

### Expected Behavior

For the request to resolve correctly and measure the routes stats.

**Comment by danew** [comment]
Weirdly if I copy the source of the plugin to a local file and re-run the request it succeeds as expected.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by danew** [comment]
Had some time to look into this today. 

The issue is due to the CORS plugin skipping the `onRequest` hook which creates the start mark, so when `measure` is called within the `onSend` hook it throws as it cannot find the mark.

Ref: https://github.com/nodejs/node/blob/main/lib/internal/perf/usertiming.js#L68

I've resolved the issue by loading the routes-stats plugin before the CORS plugin.

**Comment by danew** [comment]
> How does the cors plugin skip onRequest?

It's sending the reply before the other plugins get a change to execute
https://github.com/fastify/fastify-cors/blob/master/index.js#L75

**Comment by mcollina** [comment]
A few notes:

1. it's ok for fastify-cors to respond early, this plugin should not crash in that case.
2. fastify-cors should really _not_ respond in the `onRequest` hook: https://github.com/fastify/fastify-cors/blob/1cb4d779ecce82c30b3827b84891d6543469f1fd/index.js#L69-L74.

A PR to improve this would be highly welcomed!

**Comment by yurtaev** [comment]
Hi. i think I have the same issue with etag plugin:

```
[12:49:15.590] ERROR (20191): The "on-request-req-nmn" performance mark has not been set
    reqId: "req-nmn"
    req: {
      "method": "GET",
      "url": "/service-provider",
      "host": "127.0.0.1:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 53845
    }
    res: {
      "statusCode": 500
    }
    err: {
      "type": "DOMException",
      "message": "The \"on-request-req-nmn\" performance mark has not been set",
      "stack":
          SyntaxError: The "on-request-req-nmn" performance mark has not been set
              at getMark (node:internal/perf/usertiming:65:11)
              at calculateStartDuration (node:internal/perf/usertiming:212:13)
              at measure (node:internal/perf/usertiming:230:7)
              at Performance.measure (node:internal/perf/performance:134:12)
              at Object.<anonymous> (/Users/yurtaev/Projects/example/api-v2/api/node_modules/@fastify/routes-stats/index.js:60:19)
              at next (/Users/yurtaev/Projects/example/api-v2/api/node_modules/fastify/lib/hooks.js:295:30)
              at Object.<anonymous> (/Users/yurtaev/Projects/example/api-v2/api/node_modules/@fastify/etag/index.js:55:5)
              at next (/Users/yurtaev/Projects/example/api-v2/api/node_modules/fastify/lib/hooks.js:295:30)
              at onSendHookRunner (/Users/yurtaev/Projects/example/api-v2/api/node_modules/fastify/lib/hooks.js:317:3)
              at onSendHook (/Users/yurtaev/Projects/example/api-v2/api/node_modules/fastify/lib/reply.js:520:5)
      "name": "SyntaxError",
      "code": 12,
      "INDEX_SIZE_ERR": 1,
      "DOMSTRING_SIZE_ERR": 2,
      "HIERARCHY_REQUEST_ERR": 3,
      "WRONG_DOCUMENT_ERR": 4,
      "INVALID_CHARACTER_ERR": 5,
      "NO_DATA_ALLOWED_ERR": 6,
      "NO_MODIFICATION_ALLOWED_ERR": 7,
      "NOT_FOUND_ERR": 8,
      "NOT_SUPPORTED_ERR": 9,
      "INUSE_ATTRIBUTE_ERR": 10,
      "INVALID_STATE_ERR": 11,
      "SYNTAX_ERR": 12,
      "INVALID_MODIFICATION_ERR": 13,
      "NAMESPACE_ERR": 14,
      "INVALID_ACCESS_ERR": 15,
      "VALIDATION_ERR": 16,
      "TYPE_MISMATCH_ERR": 17,
      "SECURITY_ERR": 18,
      "NETWORK_ERR": 19,
      "ABORT_ERR": 20,
      "URL_MISMATCH_ERR": 21,
      "QUOTA_EXCEEDED_ERR": 22,
      "TIMEOUT_ERR": 23,
      "INVALID_NODE_TYPE_ERR": 24,
      "DATA_CLONE_ERR": 25
    }
```

**Comment by jsumners** [comment]
Please open a new issue with a replication.
